# Generated by Django 3.2.4 on 2021-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
