# Generated by Django 3.2.4 on 2021-06-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0002_user_data_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
