# Generated by Django 3.2.4 on 2021-09-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0003_user_data_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=200, null=True)),
                ('customerId', models.CharField(max_length=200, null=True)),
                ('productName', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=200, null=True)),
                ('productName', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=200, null=True)),
                ('productName', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=200, null=True)),
                ('productName', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
