# Generated by Django 3.2.4 on 2021-10-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0004_cart_kids_men_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('imgname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='kids',
        ),
        migrations.DeleteModel(
            name='men',
        ),
        migrations.DeleteModel(
            name='women',
        ),
    ]
