# Generated by Django 3.2.4 on 2021-10-26 08:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0005_auto_20211012_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='images/'),
        ),
    ]
