# Generated by Django 3.2.4 on 2021-10-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0008_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
